### ISSUE TITLE
remove dependency on ldap

### ISSUE THREAD

**Issue by jhoblitt** [socallinuxexpo/scale-drupal#1]
The quroum at yesterday infra migration hack section agreed that the drupal front end should stop using ldap for external user management.

/cc @irabinovitch @hriday @rgolan @jaymzh

**Comment by irabinovitch** [comment]
@jhoblitt lets got @rgolan  feedback on https://github.com/socallinuxexpo/SCALE-Planning/issues/202  first, but  it think you're likely right.

**Comment by rgolan** [comment]
I have no desire to continue with ldap. I've only used oauth as a dependency of other modules but don't have any objections to using it for sso.

**Comment by rgolan** [comment]
I'm not sure what I was thinking about when mentioning oauth as a dependency. I don't see it on the current production site now. What else needs to be done on this?

**Comment by irabinovitch** [comment]
@rgolan not sure, I assume no ldap is in use anymore. Do we want to unify logins on gauth or leave as is? We'll defer to you,

**Comment by irabinovitch** [comment]
calling this done.
