### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by zunder1990** [socallinuxexpo/scale-drupal#10]
As of 8am east coast time on 12-13-2016 both https://www.socallinuxexpo.org/ and lists.linuxfests.org are down.

@irabinovitch @hriday

**Comment by rgolan** [comment]
Seems to be firewall or routing issue. I can telnet to port 80 at localhost when ssh'd in but not from my home.

**Comment by irabinovitch** [comment]
Ya monitoring triggered over night. Just waking up now and will take a
look.

**Comment by irabinovitch** [comment]
were back up. im not clear on what removed the rules for 80, 443, and 25.  Firewall rules are maintained by chef, but theres been no chef changes in weeks according to git.  

@jaymzh heres what i did when I logged in this morning:
- Output firewall rules to /root/{firewall-121316.txt  firewallV6-121316.txt} so you can see the previous state.
- Ran chefctl in hopes that chef would reinstate the rules. It did not.
- Manually added back those ports using iptables/ip6tables:
iptables -A IN_public_allow -p tcp -m tcp --dport 80 -j ACCEPT
iptables -A IN_public_allow -p tcp -m tcp --dport 443 -j ACCEPT
ip6tables -A IN_public_allow -p tcp -m tcp --dport 80 -j ACCEPT
ip6tables -A IN_public_allow -p tcp -m tcp --dport 443 -j ACCEPT

Right now alerting goes to email. I'll look to make it SMS or something later today.
We should decide who specifically gets paged.

**Comment by jaymzh** [comment]
iptables-service upgraded installed it's own rules but didn't overwrite /etc/sysconfig/iptables (or put them back?) so Chef didn't know and thus didn't fix it.

The timestamp lines up:

`Dec 12 11:17:51 Updated: iptables-services-1.4.21-17.el7.x86_64`

That's unusual, RedHat is usually better about such things...

**Comment by jaymzh** [comment]
BTW, @irabinovitch  - those chain names don't exist in Chef's rules - it was clearly on some weird default... I restarted services and we're back on Chef-controlled rules and things look good.

**Comment by irabinovitch** [comment]
@jaymzh thanks for digging in. Ya I was just re-using the chains that were present as I didn't have time to dig into chef.   register.socallinuxexpo.org had the same issue, so I nuked  /etc/sysconfig/iptables an ran chef. Back online now. 

Do we want to submit a bug upstream? Or should we just call this done and close the ticket out.

**Comment by jaymzh** [comment]
You didn't even need to nuke it - the file was right and just bouncing the service would have been fine.

I'm going to say lets just close this and if it happens again, we'll worry about it then.
