### ISSUE TITLE
update default event to 21x in filters

### ISSUE THREAD

**Issue by kcbraunschweig** [socallinuxexpo/scale-drupal#100]
on https://www.socallinuxexpo.org/presentations-filtered
and https://www.socallinuxexpo.org/presentations-all
and https://www.socallinuxexpo.org/presentation-exporter
set SCALE event field to default to 21x

**Comment by irabinovitch** [comment]
@DrupalPhil this is hard coded somewhere on those pages i believe.

**Comment by DrupalPhil** [comment]
Updated!
