### ISSUE TITLE
Updated a previous talk abstract and page no longer renders

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-drupal#101]
Page: https://www.socallinuxexpo.org/scale/19x/presentations/building-scales-openwrt-conference-wifi

I was in the speaker portal submitting a new talk for the 2023 CFP and changed my 19x talk after noticing a small typo in the abstract. The page no longer renders correctly.

**Comment by DrupalPhil** [comment]
The URL Patterns used for Presentation nodes were using the site slogan instead of the event set on the node, itself.

I've updated the URL pattern for Presentations.
