### ISSUE TITLE
2023 speaker pages showing access denied suddenly

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#113]
2023 speaker pages are showing access denied suddenly.
Here are a few examples that dont work if you aren't logged in.

https://www.socallinuxexpo.org/scale/20x/speakers/ibrar-ahmed
https://www.socallinuxexpo.org/scale/20x/speakers/hamid-akhtar
https://www.socallinuxexpo.org/scale/20x/speakers/roller-angel

**Comment by DrupalPhil** [comment]
This is the utility function I optimized previously. I rebuilt the function based (mostly) on the comments in the code. I misunderstood it to mean that users should only be able to see speakers from the _current_ event, not the event in the url.

The latest commit addresses this.
