### ISSUE TITLE
can we add topic to the CSV export of talks?

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#116]
We have two views that export talks for a given event as CSV:

1) https://www.socallinuxexpo.org/presentation-exporter.csv
2) https://www.socallinuxexpo.org/presentation-accepted-exporter.csv

the first one does not include track, but the second one does.  can we add the topic filed to the first one as well?

Code appears to be here: https://github.com/socallinuxexpo/scale-drupal/blob/master/httpdocs/sites/all/modules/custom/features/scale_presentation/scale_presentation.views_default.inc

**Comment by DrupalPhil** [comment]
Added!

Phil Smith
954-558-5022

**Comment by DrupalPhil** [comment]
No, it's all set!

Phil Smith
954-558-5022
