### ISSUE TITLE
Speaker link not working for Flynn

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#117]
For this presentation page, clicking Flynn's name brings you to the full speeaker list rather than his speaker page:

Presentation: https://www.socallinuxexpo.org/scale/21x/presentations/service-mesh-101-meet-service-mesh

It appears to link to https://www.socallinuxexpo.org/scale/21x/speakers/--flynn instead of https://www.socallinuxexpo.org/scale/21x/speakers/flynn

**Comment by irabinovitch** [comment]
CC @kcbraunschweig 

@DrupalPhil any ideas?

**Comment by irabinovitch** [comment]
@DrupalPhil any thoughts on this one?

**Comment by DrupalPhil** [comment]
Addressed. The view was configured to render the name poorly.

**Comment by irabinovitch** [comment]
Is it possible this fix broke talks with multiple speakers? Eg this one has two speakers but only shows (1) name. 

https://www.socallinuxexpo.org/scale/21x/presentations/cloud-native-data-and-model-lifecycle-management-ai
