### ISSUE TITLE
Saturday schedule

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#118]
Could I get a second pair of eyes on the Saturday schedule for SCALE 21x? It doesn't seem to be loading, so I think maybe I got a query wrong that I'm not obviously noticing.

Page: https://www.socallinuxexpo.org/scale/21x/schedule/saturday
Panel: https://www.socallinuxexpo.org/admin/structure/pages/nojs/operation/page-schedule_21x/handlers/page_schedule_21x__panel_context_959b8381-bb61-4890-92ac-6c25983e9889/content

The preview implies data should be showing up for ballroom H, but nothing is when I look at the page as a logged in or anonymous user. 

Thur, Fri and Sun load fine.  Wondering what I missed as they look identify to me minus the date change.

**Comment by kcbraunschweig** [comment]
I found the issue, the selection rule had a typo that referenced friday instead of saturday. Working now.
