### ISSUE TITLE
Talks no longer list multiple speakers 

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#120]
I'm not sure if related to the fix in #117 , however talks with 2+ speakers now only list the first speakers name. 

Eg this one has two speakers but only shows (1) name.  pictures seem unaffected only speaker names.

https://www.socallinuxexpo.org/scale/21x/presentations/cloud-native-data-and-model-lifecycle-management-ai

**Comment by irabinovitch** [comment]
@DrupalPhil FYI

**Comment by irabinovitch** [comment]
CC @kcbraunschweig

**Comment by irabinovitch** [comment]
@DrupalPhil is this related to the fix we did for Flynn?

**Comment by DrupalPhil** [comment]
Yes, it was... I didn't realize there was the potential for multiple speakers here.

All set:
- https://www.socallinuxexpo.org/scale/21x/presentations/cloud-native-data-and-model-lifecycle-management-ai
- https://www.socallinuxexpo.org/scale/21x/presentations/service-mesh-101-meet-service-mesh
