### ISSUE TITLE
safety page is year-ified

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/scale-drupal#124]
Can we make the safety page (http://www.socallinuxexpo.org/safety) not link to a 15x-specific page? It should be, ideally, year-agnostic, or at the very least, skinned for the current year.

**Comment by DrupalPhil** [comment]
All set:
https://www.socallinuxexpo.org/scale/anti-harassment-policy

**Comment by jaymzh** [comment]
Can we please make that /safety (or make /safety point to that) to match the signs we put up?

**Comment by DrupalPhil** [comment]
I'm not sure what signs exist. Does this look right?
https://www.socallinuxexpo.org/scale/safety

**Comment by jaymzh** [comment]
No. As I said, the signs say "http://www.socallinuxexpo.org/safety" - that's the URL that has to work. :)

**Comment by DrupalPhil** [comment]
Ah. smh. Sorry, when I came back to this ticket, I failed to read the very first issue comment; only the latest.

I'm thinking there's something other than Drupal at work here. I have the URL alias for /node/2898 set to /safety but it's doing a 302 redirect to /scale/15x/anti-harassment-policy.

Can someone with access to the server look at any apache/nginx configuration for this issue? Or perhaps there's a CDN/reverse proxy in place handling this?

**Comment by jaymzh** [comment]
Ah yes. Probably apache. Will look.

⁣Get BlueMail for Android ​

**Comment by jaymzh** [comment]
Doh, /safety is indeed an apache redirect.

https://github.com/socallinuxexpo/scale-chef/pull/309 will nuke the redirect.

Before I merge it - you've set drupal to serve this on `/safety`, yeah?

**Comment by DrupalPhil** [comment]
Yes

**Comment by jaymzh** [comment]
Ugh. The redirect is still there. I think CloudFlare has cached the redirect, as I tried a new browser, and it gets redirected, but `/safety` never shows up in the access logs. @irabinovitch - I don't believe I have access to CF, can you give me access so I can fix?

In the meantime, @DrupalPhil - can we make both paths work (`/scale/15x/anti-harassment-policy` so that the existing redirect works and `/safety` for when we fix it)?

**Comment by DrupalPhil** [comment]
Seems to be working for me, today.

Do you want me to remove the second redirect?
- https://www.socallinuxexpo.org/safety
- https://www.socallinuxexpo.org/scale/15x/anti-harassment-policy

**Comment by jaymzh** [comment]
Cache timeout for the win!

Let's leave the second redirect, incase people have it bookmarked. Plus I still think that path is linked from old blog posts.

Everything looks great now, thanks!
