### ISSUE TITLE
Old reference to 20x in BoF page

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-drupal#126]
## Description

Old reference to 20x in BoF page: https://www.socallinuxexpo.org/scale/21x/birds-feather-sessions

> Please use the #scale20x tag when promoting your meeting or when discussing a BoF you intend to attend, whichever social media you're using. We will once again have sponsored BoFs for FLOSS topics and companies.

**Comment by DrupalPhil** [comment]
Fixed.
