### ISSUE TITLE
MySQL2 deprecation

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/scale-drupal#129]
Hey @DrupalPhil - do you have time to test the codebase against MySQL2? AWS is deprecating 2 in 6 months. Notice below:

Hello,

You are receiving this message because you have one or more Amazon Aurora MySQL clusters running a version of Aurora MySQL 2 (with MySQL 5.7 compatibility) on a provisioned instance in the US-EAST-1 Region. If you are running Amazon Aurora MySQL 2 (with MySQL 5.7 compatibility) in an Aurora Serverless v1 cluster, this communication does not apply to you.

Amazon Aurora MySQL 2 (with MySQL 5.7 compatibility) will reach end of standard support on October 31, 2024. We are providing you with a 6-month reminder, following up from our previous 12-month notice, so you have sufficient time to upgrade your database cluster(s). Please note that upgrading between major versions requires more extensive planning and testing than for a minor version and the process can take substantial time.

We recommend that you upgrade your databases to the latest patch of the default minor version of Amazon Aurora MySQL 3 (currently Aurora MySQL 3.04) or higher, at your earliest convenience before October 31, 2024. For how to do the upgrades please consult our documentation [1]. Upgrades may be performed using in-place upgrade [2], snapshot and restore [3], or a high availability blue-green upgrade technique which can be fully managed using Amazon RDS Blue/Green Deployments [4]. The amount of downtime your system will experience depends on the upgrade technique chosen, as well as properties of your schema.

Major version upgrades will require downtime and might require manual intervention and application changes. We will send you updates and reminders before the standard support deadline. You can find the latest information needed to plan your upgrade in our 'User Guide for Aurora' [5].

The affected clusters are listed in the 'Affected resources' tab of your AWS Health Dashboard. You can also find clusters which are affected by this deprecation notice by referring to the following user guide [6].

Amazon Aurora MySQL provides you with one year of free extended support over community MySQL 5.7, that reached end of life on October 31, 2023. If you need more time to complete the upgrades, you can use Amazon RDS Extended Support [7] for Aurora MySQL 2. RDS Extended Support [8] for Aurora is a paid service [9] that will provide up to 28 additional months of support for Aurora MySQL 2 until the end of extended support in February 2027. After October 31, 2024 all your databases continue running Aurora MySQL 2 will be automatically enrolled in RDS Extended Support. Charges for RDS Extended Support will start accruing from December 1, 2024. RDS Extended Support will only be offered for Aurora MySQL minor versions 2.11 and 2.12. If you plan to use Amazon Aurora MySQL 2 beyond end of standard support, please plan to be running your database(s) on one of these minor versions before October 31, 2024. If your databases are not running Aurora MySQL minor versions 2.11 or 2.12 by October 31, 2024 they will be upgraded before being enrolled into RDS Extended Support. This upgrade will occur during your maintenance window and cannot be turned off.

Should you have any questions or concerns, the AWS Support Team is available on AWS re:Post [10] and via AWS Support. [11]

[1] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.MajorVersionUpgrade.html#AuroraMySQL.Updates.MajorVersionUpgrade.2to3
[2] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.MajorVersionUpgrade.html#AuroraMySQL.Upgrading.Procedure
[3] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-restore-snapshot.html
[4] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/blue-green-deployments.html
[5] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.MySQL57.EOL.html
[6] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.MySQL57.EOL.html#find-cluster
[7] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/extended-support.html
[8] https://aws.amazon.com/blogs/database/introducing-amazon-rds-extended-support-for-mysql-databases-on-amazon-aurora-and-amazon-rds/
[9] https://aws.amazon.com/rds/aurora/pricing/#Amazon_RDS_Extended_Support_costs
[10] https://repost.aws/
[11] https://aws.amazon.com/support

Sincerely,
Amazon Web Services

Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210

---
Reference: https://health.aws.amazon.com/health/home?region=us-east-1#/event-log?eventID=arn:aws:health:us-east-1::event/RDS/AWS_RDS_PLANNED_LIFECYCLE_EVENT/AWS_RDS_PLANNED_LIFECYCLE_EVENT_eb3a6a9c7f7ac3e52d669f10ca6cf9a1fba47ae95059613d292550375a81905f&amp;eventTab=details

**Comment by jaymzh** [comment]
@DrupalPhil - this EOL is coming up this month...

**Comment by DrupalPhil** [comment]
I ran this installation on MYSQL 5.7.24 just fine. 

I'd recommend spinning up a development environment that leverages MYSQL 5+ and testing it. Locally, the site runs just fine on 5+.

**Comment by jaymzh** [comment]
Phil and I caught up offline, but just to keep the issue uptodate, 5.7 (Aurora MySQL 2) current version, and we have to test MySQL 8 (Aurora SQL 3), and Phil said he'd test that ASAP.

**Comment by DrupalPhil** [comment]
I can confirm the D7 site will run on MySQL 8 just fine.

![Status_report___SCALE_22x](https://github.com/user-attachments/assets/8f0af121-f676-4b13-8a88-718e71e2dfd5)

**Comment by jaymzh** [comment]
All databases updated.

Thanks!
