### ISSUE TITLE
SCALE 14X site using 15X template

### ISSUE THREAD

**Issue by leizleiz** [socallinuxexpo/scale-drupal#13]
This is rather confusing. I searched for SCALE 15X and got links to SCALE 14X, e.g. https://www.socallinuxexpo.org/scale/14x/speakers/richard-wareing

Where currently:
- The title says "RIchard Wareing | SCALE 15X"
- The logo is for 15X
- The top menu links to 15x URLs. There's no way to navigate the 14X site.

OTOH, the linked talk, https://www.socallinuxexpo.org/scale/14x/presentations/scaling-glusterfs-facebook displays everything as expected.

**Comment by irabinovitch** [comment]
Seem similar to https://github.com/socallinuxexpo/SCALE-Planning/issues/119 

@rgolan can you help take a look

**Comment by irabinovitch** [comment]
Seeing this in google search results as well. https://cl.ly/0W1f23291V2B

**Comment by rgolan** [comment]
The problem is that we don't create separate users or user pages each year. Now that we are in 15x, the paths are different for the one user page per user. If we continue with this arrangement, perhaps we shouldn't make user pages event specific taking the scale/15x/ out of the path.

**Comment by irabinovitch** [comment]
Could we use the path as logic for what title / template to use?
