### ISSUE TITLE
clicking individual speaker names brings up full speaker list

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#14]
Have noticed this with a few:

Allison:
https://www.socallinuxexpo.org/scale/15x/speakers/alison-chaiken

VM:
https://www.socallinuxexpo.org/scale/15x/presentations/passing-baton-succession-planning-foss-leadership

**Comment by rgolan** [comment]
I can fix the problem with Alison Chaiken for example by recreating the user page aliases to use the 15x path. There is another related problem I see. some users like Jono Bacon have used two separate user IDs so not all their previous presentations will appear on their user pages. We would have to merge those to use a single a user. Do you care about doing this?

**Comment by irabinovitch** [comment]
Merging would be nice to get the past talks on their profile, but I dont have a sense of how much work that is.

**Comment by DrupalPhil** [comment]
Looks like we're using this pattern for user profiles:
http://scale.lndo.site/scale/**{scale_event}**/speakers/matt-yonkovit

The links you provided are dynamically replacing the scale_event via context. If we are ok with changing this pattern to something evergreen, we can fix this.

Something like:
http://scale.lndo.site/scale/speakers/matt-yonkovit

Any issues with this approach?
