### ISSUE TITLE
add company below featured speaker name

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#16]
Can we add the company and title for speaker below their name?

https://cl.ly/163j0f2X373c

**Comment by rgolan** [comment]
I can certainly add those fields but I can they were shown before and were turned off at someone's request. If you confirm you want them showing, I'll do it.

**Comment by irabinovitch** [comment]
hm. didn't remember we removed them. do you remember who asked for that? hoping it wasn't me? :)

**Comment by rgolan** [comment]
I don't know but it's easy to turn them on or off. I'll turn them on now.

**Comment by irabinovitch** [comment]
Thanks. Looks like we have an extra space ahead of first name?

**Comment by rgolan** [comment]
I turned them on but because of the different length job titles and organizations, they don't make a clean grid. Any suggestions?

**Comment by rgolan** [comment]
Removed the extra padding from the names.

**Comment by irabinovitch** [comment]
is there a particular length limit we need to hit to keep it as a grid?

**Comment by irabinovitch** [comment]
could we force it to wrap to the next line if its too long?

**Comment by rgolan** [comment]
For now what I've done is fixed the text display below to 3 lines and applied an overflow hidden to those lines.

**Comment by irabinovitch** [comment]
Thanks
