### ISSUE TITLE
Tech Committee Changes

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/scale-drupal#17]
There are now two tech committees: the "online services" (mail/web/etc.) and "conference services" (networking, wifi, et. al)... Can we get these split on the site? @hriday - we never formally "named" these, but we should update the page.... I don't feel strongly about names, so feel free to suggest better names.

For my team, I'm the chair and the other member is Davide Cavalca.

Thanks!

**Comment by rgolan** [comment]
I’ve updated the Contact Us page. Any further corrections?

—
Ron Golan
rgolan@superconcentrated.com

**Comment by jaymzh** [comment]
It looks like the "p" in my name and the "hil dibowitz" are two separate links...  other than that it all looks good.

**Comment by rgolan** [comment]
Fixed that.

—
Ron Golan
rgolan@superconcentrated.com
