### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/scale-drupal#18]
Can I be made an owner/editor of the code of conduct page so I can update contact information and keep it up to date (as the diversity chair)? Thanks!

**Comment by rgolan** [comment]
Phil,

As you know, you have two user accounts. Which do you want to own the Code of Conduct page?

	• Phil Dibowitz (phil@socallinuxexpo.org)
	• Phil Dibowitz (phil@ipom.com)

Do you want to merge one user into the other?

—
Ron Golan
rgolan@superconcentrated.com

**Comment by jaymzh** [comment]
Yeah - phil@socallinuxexpo.org is my "real" one - can we delete the other one?

**Comment by rgolan** [comment]
I deleted the ipom one. Please try to edit the Anti Harassment Policy page now and let me know if you can.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by jaymzh** [comment]
Looks great, thanks so much!
