### ISSUE TITLE
Add NOODP or nosnippets meta tag

### ISSUE THREAD

**Issue by leizleiz** [socallinuxexpo/scale-drupal#19]
At SCALE 15X, we noticed a Google search for: SCALE 15X returns a link to our website with "At the Davidson Conference Center on the University of Southern California campus..." as the snippet for the website. According to [1], this comes from [2]. So to remove it we need to use the NOODP meta tag, or use nosnippets to remove auto-generated snippets altogether.

[1] https://support.google.com/webmasters/answer/35624
[2] http://www.dmoz.org/Computers/Open_Source/Conferences/

**Comment by irabinovitch** [comment]
@leizleiz I think this is fixed?

**Comment by irabinovitch** [comment]
@leizleiz this look ok to you now?
