### ISSUE TITLE
16x page shows 17x info

### ISSUE THREAD

**Issue by kylerisse** [socallinuxexpo/scale-drupal#20]
Nothing major but if you visit https://www.socallinuxexpo.org/scale/16x you'll see the 17x image up top along with the dates March 7-10, 2019, rather than the 16x info. The page title also reflects 17x. 

This doesn't appear to affect 13x - 15x but 11x and 12x show the 16x logo. Hope this info is useful.

**Comment by rgolan** [comment]
Thanks for catching that.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
Most of the 16x pages have a 17x title tag as well which is resulting in some confusing google search results.

**Comment by rgolan** [comment]
I just added a meta tag module that should fix the head title issue.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
@kylerisse Prior to SCALE 13x use used a different url structure.
You want https://www.socallinuxexpo.org/scale11x/ and https://www.socallinuxexpo.org/scale12x/

**Comment by kylerisse** [comment]
Understood. Apologies for not following. That means this issue is resolved. Thanks!
