### ISSUE TITLE
Build Schedule

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#23]
Hi Ron,

I've started . filling in session times. But I can't find the URL for the schedule. I'd expect it to be at:
https://www.socallinuxexpo.org/scale/17x/schedule/friday

Which doesn't seem to 404, but does give me the home page.

Ilan

**Comment by rgolan** [comment]
Hi Ilan,

Should I turn on all rooms in the schedule for now? Also do you want me to limit the visibility to certain roles for now?

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
As long as it's not linked it's fine to be public.
And ya if you turn on all the rooms I can send you a list to turn offer
after I'm done building the schedule.

**Comment by rgolan** [comment]
Hi Ilan,

The standard paths should work now for the schedules. They are publicly visible but there are no links to those pages except from the schedule pages themselves.  I hope nothing indexes any wrong rooms or times.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
@rgolan Thanks. Overall looking good. A few things I need help with though:

* I can't get the MariaDB workshop to appear on Thursday in room 103 (https://www.socallinuxexpo.org/scale/17x/presentations/mariadb-workshop)
*  Can we add Room 205 Fri-Sun?

Can we remove/disable the following rooms?
===
207 - all days
208 - all days
ballroom I & J - all days
Ballroom C - Thursday
DE - Thursday
F - Thursday
G - Thursday
H - Thursady
GH - all days
IJ - all days

**Comment by rgolan** [comment]
I’ve fixed the Thursday room 102 display problem and removed the listed rooms from the days given.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
@rgolan  Thanks. Can we hide G & H on Friday? Once thats done lets link the schedule from the header.  Thanks!

**Comment by rgolan** [comment]
Hi Ilan,

This is done.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
Thanks.  I just noticed that
https://www.socallinuxexpo.org/scale/17x/schedule links to 16x though.

**Comment by irabinovitch** [comment]
Thanks!  All set here.
