### ISSUE TITLE
scroll silver sponsors

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#25]
We have a much larger than usual # of silver sponsors this year. Could we make the logos scroll like we have for media sponsors in the past? The page currently scrolls fairly far down.

**Comment by rgolan** [comment]
I set up rotation with those but because of the variance in logo height, it shows some blank space at times. Please take a look and let me know what you think.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
Is there a size we should target for logos to make that work better?

**Comment by irabinovitch** [comment]
@rgolan Is there a size we should target for logos to make that work better?
