### ISSUE TITLE
Keynote

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#26]
Can we update the topics listing to offer a keynote field?

https://www.socallinuxexpo.org/scale/17x/presentations/growing-hashicorp-dorm-room-oss

**Comment by rgolan** [comment]
I’ve added the Keynote topic but be aware that anyone that can edit presentations can select it.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
Thanks!
