### ISSUE TITLE
access denied for der hans

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#30]
When one clicks Hans name on his presentations[1][2] they are presented with an access denied error.  I've tried swapping out the speaker as one of the following, but they all have the same result:
der hans1 [uid:4066]
der hans [uid:498]
LuftHans Kugler [uid:422]

They link to https://www.socallinuxexpo.org/scale/17x/speakers/der-hans 

From the [speakers page](https://www.socallinuxexpo.org/scale/17x/speakers) we link to https://www.socallinuxexpo.org/scale/17x/speakers/der-hans-1 which loads fine.

Similarly the presentations page links to the same working der-hans-1 link.

Can we merge all the users into der hans1? It seems to have the latest bio and the most talks?

[1] https://www.socallinuxexpo.org/scale/17x/presentations/software-management-debian-and-ubuntu
[2] https://www.socallinuxexpo.org/scale/17x/presentations/device-and-personal-privacy-technology-roundup

**Comment by irabinovitch** [comment]
Drew Moseley has a similar issue. Likely due to multiple user names. 
https://www.socallinuxexpo.org/scale/17x/speakers/drew-moseley

**Comment by rgolan** [comment]
I moved all Hans’ presentations to a single user and blocked the other 2 users. I think that works. I also fixed Drew Moseley.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
Thanks.

**Comment by irabinovitch** [comment]
Looks like we're having the same issue for Jason Hibbets

https://www.socallinuxexpo.org/scale/17x/speakers/jason-hibbets

**Comment by rgolan** [comment]
Should be fixed now. I found the easiest way to fix this there is only one user profile is to add an additional path alias with the 17x in it.
