### ISSUE TITLE
HAM Exams link directs to 15x link

### ISSUE THREAD

**Issue by kylerisse** [socallinuxexpo/scale-drupal#34]
The HAM Exams link on the Events page redirects to a 15x URL (https://www.socallinuxexpo.org/scale/15x/scale15x-ham-exams). Oddly enough, the description reflects the correct year.

Steps to recreate:
1. Start at https://www.socallinuxexpo.org/scale/17x/events
2. Scroll to the bottom and click on "SCALE17X HAM Exams"
3. Find yourself redirected to a 15x URL and looking at the 15x logo and sponsor scrolls

This does not seem to be the case for any of the other events, they all link to 17x pages.

**Comment by irabinovitch** [comment]
@hriday I think you might have updated the 15x version rather than creating a new 17x page.
I've renamed the page, but my guess is we've now lost the 15x page.

**Comment by kylerisse** [comment]
Thanks @irabinovitch
