### ISSUE TITLE
display presentation links

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#35]
Hi Ron,

Do we need to do anything to unhide links to presentation attachments now that the show is over?

Thanks,
Ilan

**Comment by irabinovitch** [comment]
Nevermind. It was caching!.

**Comment by rgolan** [comment]
Hi Ilan,

I wanted to give you a heads up. I’m going to be away between April 9 and May 6. If you need anything from me, let me know soon.

—
Ron Golan
rgolan@superconcentrated.com
