### ISSUE TITLE
Need adjustment to hosting

### ISSUE THREAD

**Issue by rgolan** [socallinuxexpo/scale-drupal#5]
I had to set the views at the following to show only 20 presentations at a time.

https://www.socallinuxexpo.org/presentations-filtered

https://www.socallinuxexpo.org/presentations-all

They were both showing white screens when set to show everything. If we can adjust whatever in the hosting was causing the white screens, I can set it back. Both views rendered successfully on my dev machine while showing everything but I have the PHP memory set to 256M.

**Comment by irabinovitch** [comment]
@jaymzh want to take a stab at this?

**Comment by rgolan** [comment]
I can reset the views back to what they were if it would help. We need to get a staging site set up.

**Comment by jaymzh** [comment]
@irabinovitch what's the request here, just to bump the PHP memory? Is that in the php.ini?

**Comment by irabinovitch** [comment]
I believe so.

**Comment by jaymzh** [comment]
Alright - we currently don't own the php.ini in Chef, so I changed it manually. If that fixed, let me know and I'll chef-ify that.

**Comment by jaymzh** [comment]
@rgolan  - that fix it for ya?

**Comment by rgolan** [comment]
It did fix it.

—
Ron Golan
rgolan@superconcentrated.com
