### ISSUE TITLE
SCALE Drupal Apache error log filled with same error

### ISSUE THREAD

**Issue by rgolan** [socallinuxexpo/scale-drupal#6]
The Apache errors.log is filled with

[Fri Nov 18 16:02:46.361004 2016] [access_compat:error] [pid 31450] [client 2001:4800:7818:104:be76:4eff:fe04:4215:45908] AH01797: client denied by server configuration: /home/drupal/scale-drupal/httpdocs/server-status

Do we need to make a change to the Apache configuration to allow this?

**Comment by irabinovitch** [comment]
Yes, will take a look.
