### ISSUE TITLE
Drupal logo on SCALE site

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-drupal#7]
It appears the header on every page has a drupal logo in the top left hand corner:
https://www.socallinuxexpo.org/sites/all/themes/custom/scale15x/logo.png

Can we set this back to Troy?

**Comment by irabinovitch** [comment]
CC @leizleiz as he needs the right logo for registration.

**Comment by rgolan** [comment]
I've updated the menu icon.

**Comment by irabinovitch** [comment]
Thanks @rgolan 
@leizleiz when you have a moment, can you do the same in scalereg?

**Comment by leizleiz** [comment]
Done. Oh, I was expecting the image URL to not change...

**Comment by leizleiz** [comment]
Speaking of Drupal icons, the favicon on https://www.socallinuxexpo.org/scale/14x, and most other pages points to https://www.socallinuxexpo.org/misc/favicon.ico, which is a Drupal icon as well.

https://www.socallinuxexpo.org/scale/13x/ points to https://www.socallinuxexpo.org/sites/default/files/favicon_0.png which says 13x, and https://www.socallinuxexpo.org/scale12x/ has its dice logo.

**Comment by irabinovitch** [comment]
@rgolan can you help update the favicons?

**Comment by rgolan** [comment]
I changed the favicon for 14x and 15x to a Troy image

**Comment by irabinovitch** [comment]
Cool. Thanks.
