### ISSUE TITLE
Title broken

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/scale-drupal#75]
From an attendance...

hi Phil,

It looks like the SCaLE website frontpage has its HTML title truncated:

      <title>| 20x</title>

The Wayback Machine shows the earlier correct title:

  <title>SCALE 20x | 20x</title>

Google still has the old correct title cached, but Duck Duck Go shows
the current incorrect one (screenshot attached)

hth,
Thomas

**Comment by DrupalPhil** [comment]
I'll take a look

Phil Smith
954-558-5022

**Comment by DrupalPhil** [comment]
The title was only broken on the 20x landing page ... `/scale/20x`

**Comment by DrupalPhil** [comment]
https://github.com/socallinuxexpo/scale-drupal/pull/76
