### ISSUE TITLE
New demographics questions

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/scale-drupal#78]
For the 2024 site, before we open CFP, can we please update the Demographic questions to this:

https://docs.google.com/spreadsheets/d/10D-eIJK2O-Xhvwc4cp0oJuWH2lhwAFfwzj7yAr1gUMs/edit#gid=0

**Comment by DrupalPhil** [comment]
Can you share where the current approach exists? I'm not aware of how the questions are delivered or stored.

**Comment by irabinovitch** [comment]
@DrupalPhil when you create a new account [here](https://www.socallinuxexpo.org/user/register) it asks you some questions which get attached to your user.

**Comment by irabinovitch** [comment]
![Screenshot 2023-07-18 at 7 02 26 PM](https://github.com/socallinuxexpo/scale-drupal/assets/289654/37d6440f-5769-40ef-a565-9cdccec2ae30)

**Comment by DrupalPhil** [comment]
Let me know when the latest code is pulled in so I can import the feature.

**Comment by irabinovitch** [comment]
done

**Comment by DrupalPhil** [comment]
This is complete.

**Comment by irabinovitch** [comment]
It looks like "prefer not to say" fails registration.

**Comment by irabinovitch** [comment]
Also income seems to not include a prefer not to say option.

**Comment by irabinovitch** [comment]
Confirmed this works now. Thanks!
