### ISSUE TITLE
Newsletter sign up code

### ISSUE THREAD

**Issue by rgolan** [socallinuxexpo/scale-drupal#8]
Chris Smith reported the code for the newsletter signup is breaking the javascript that allows one to revise their votes on presentations. Do we have an update on this code to work with whatever is providing the newsletter list or do we have a clean version of this code? I think it was provided to me by Stu years ago. Chris suspected it was a problem with the commented out parts and addFieldToCheck() being undefined.

<form method="post" action="https://lists.linuxfests.org/lists/?p=subscribe&id=1" name="subscribeform" id="subscribeform"><input type="hidden" name="formtoken" value="0e1864a04f78f7f1ad54f64da8fb58c9" /><div class="required">Email</div>
<div class="attributeinput"><input type="text" name="email" value="" size="40" /></div>
<script language="Javascript" type="text/javascript">
<![CDATA[// ><!]]>
</script><div class="required">Confirm your email address</div>
<div class="attributeinput"><input type="text" name="emailconfirm" value="" size="40" /></div>
<script language="Javascript" type="text/javascript">
<![CDATA[// ><!]]></script><span class="attributeinput"><input type="checkbox" name="htmlemail" value="1" hidden="true" /></span><span class="attributeinput"><input hidden="true" type="checkbox" name="attribute2" value="on" /></span><div class="attributeinput"><p class="hidden"><input type="hidden" name="list[1]" value="signup" /><input type="hidden" name="listname[1]" value="SCALE-mailing" /></p>
<div style="display:none"><input type="text" name="VerificationCodeX" value="" size="20" /></div>
<p><span><input type="submit" name="subscribe" value="Subscribe" onclick="return checkform();" /></span></p></div></form>

**Comment by rgolan** [comment]
I just disabled the newsletter signup block of any authenticated user as a workaround.

**Comment by rgolan** [comment]
Update

I was able to change my votes with a user with the same permissions as Chris Smith on both my local and production. I also tried after reenabling the newsletter signup block and also able to successfully change votes. I've asked Chris for any further information he could provide.

**Comment by irabinovitch** [comment]
Do we think this is still a problem?

**Comment by rgolan** [comment]
I was never able to replicate the issue and Chris was the only one to report a problem. I think we can close this.
